### ISSUE TITLE
Improve drawing function interface

### ISSUE THREAD

**Issue by FASTSHIFT** [kikuchan/pngle#5]
Can be improved to row-by-row pixel data instead of outputting pixels one by one.
The pngle library can apply for a single-line buffer to buffer pixel data, and use the `on_draw` callback to notify the user when buffer is full, reducing the number of calls to the `on_draw` callback function, improve operational efficiency.

For example 
```c
static void on_draw(pngle_t* pngle, uint32_t x, uint32_t y, uint32_t w, uint32_t h, uint8_t rgba[4])
{
    disp_draw_pixel(x, y, (uint32_t*)rgba);
}
```
->
```c
static void on_draw(pngle_t* pngle, uint32_t row, const pngle_pixel_t* pixel_buf, size_t buf_len)
{
    disp_set_cursor(0, row);
    disp_put_pixels((uint32_t*)pixel_buf, buf_len);
}
```

**Comment by kikuchan** [comment]
Thank you for your feedback!
Unfortunately, I can't by design...

Pngle is a pixel based because of some reasons;
1. It aims to minimize memory usage
2. support interlaced image
3. easy to read/embbed
4. act as a thin layer of decoding steps

It means, if you need a line buffer you need to either;
* drop support of interlaced image
* allocate a full frame buffer (for interlaced image)
